#!/bin/sh

#
# Do at least a cursory investigation that things are in order.
#
if [ ! -f .config ] ; then
	echo "You need to run ./configure and make in ${PWD} first!"
	exit 1;
fi

#
# source all the Make variables as Shell variables
#
eval `cat .config | sed -e '/^#/d' -e '/^$/d' -e 's/=/="/' -e 's/$/"/'`

#
# and run Java appropriately.
#
exec ${JAVA} \
	-classpath ${GNOME_JARS}:${XOM_JARS}:${JUNIT_JARS}:tmp/classes/ \
	quill.client.Quill $*
